
//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     Mudanças neste arquivo podem causar comportamento incorreto e serão perdidas
//     quando o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
module Api.Produto.Excluir {
    export interface Command {
        id: number;
    }
}

module Api.Produto.InserirEditar {
    export interface Command {
        id?: number;
        descricao?: string;
        valor: number;
        caminhoImagem?: string;
        nomeImagem?: string;
    }

    export interface Query {
        id: number;
    }
}

module Api.Produto.Listar {
    export interface Dto {
        products?: ProdutoDto[];
    }

    export interface ProdutoDto {
        id: number;
        descricao?: string;
        valor: number;
    }

    export interface Query {
    }
}

export default Api
