/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import '@tempusdigital/ionic';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface MenuPage {}
  interface MenuPageAttributes extends StencilHTMLAttributes {}

  interface ProdutoInserirEditar {
    'produtoId': number;
  }
  interface ProdutoInserirEditarAttributes extends StencilHTMLAttributes {
    'produtoId'?: number;
  }

  interface ProdutoListar {}
  interface ProdutoListarAttributes extends StencilHTMLAttributes {}

  interface ToastComponent {
    'color': string;
    'duration': number;
    'message': string;
    'show': () => Promise<void>;
  }
  interface ToastComponentAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'duration'?: number;
    'message'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'MenuPage': Components.MenuPage;
    'ProdutoInserirEditar': Components.ProdutoInserirEditar;
    'ProdutoListar': Components.ProdutoListar;
    'ToastComponent': Components.ToastComponent;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'menu-page': Components.MenuPageAttributes;
    'produto-inserir-editar': Components.ProdutoInserirEditarAttributes;
    'produto-listar': Components.ProdutoListarAttributes;
    'toast-component': Components.ToastComponentAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMenuPageElement extends Components.MenuPage, HTMLStencilElement {}
  var HTMLMenuPageElement: {
    prototype: HTMLMenuPageElement;
    new (): HTMLMenuPageElement;
  };

  interface HTMLProdutoInserirEditarElement extends Components.ProdutoInserirEditar, HTMLStencilElement {}
  var HTMLProdutoInserirEditarElement: {
    prototype: HTMLProdutoInserirEditarElement;
    new (): HTMLProdutoInserirEditarElement;
  };

  interface HTMLProdutoListarElement extends Components.ProdutoListar, HTMLStencilElement {}
  var HTMLProdutoListarElement: {
    prototype: HTMLProdutoListarElement;
    new (): HTMLProdutoListarElement;
  };

  interface HTMLToastComponentElement extends Components.ToastComponent, HTMLStencilElement {}
  var HTMLToastComponentElement: {
    prototype: HTMLToastComponentElement;
    new (): HTMLToastComponentElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'menu-page': HTMLMenuPageElement
    'produto-inserir-editar': HTMLProdutoInserirEditarElement
    'produto-listar': HTMLProdutoListarElement
    'toast-component': HTMLToastComponentElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'menu-page': HTMLMenuPageElement;
    'produto-inserir-editar': HTMLProdutoInserirEditarElement;
    'produto-listar': HTMLProdutoListarElement;
    'toast-component': HTMLToastComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
